# SonarCloud configuration for Go
sonar.projectKey=ernsoylu_tup
sonar.organization=ernsoylu

sonar.sources=cmd,internal
sonar.tests=
# No tests for the MVP just yet, so keeping empty

# Coverage
sonar.go.coverage.reportPaths=coverage.out
