sonar.projectKey=ernsoylu_tup
sonar.organization=ernsoylu
sonar.sources=cmd,internal

# Ignore test coverage for the initial prototype
sonar.coverage.exclusions=**/*.go

# Table-driven Go tests often trip CPD thresholds; exclude them from duplication.
sonar.cpd.exclusions=**/*_test.go
